#ifndef PACKET_ID_H
#define PACKET_ID_H

namespace Packets
{
enum EG_Packets
{
    EG_MIN_ID = 1, 
///---SETTERS---
    EG_SET_UID, EG_SET_SOCIAL_NET, EG_SET_SOCIAL_ID, EG_SET_FIRST_NAME, EG_SET_LAST_NAME, 
    EG_SET_NICK_NAME, EG_SET_SEX, EG_SET_MUSIC, EG_SET_SOUND, EG_SET_ADMIN, EG_SET_LAST_JOIN_UTIME, 
    EG_SET_REGISTRATION_UTIME, EG_SET_LANGUAGE, EG_SET_INVITE_FRIENDS_COUNT, EG_SET_FRIENDS_DATA, 
    EG_SET_APP_FRIENDS_DATA, EG_SET_MONEY, EG_SET_GOLD, EG_SET_EXP, EG_SET_LVL, 
///---GETTERS---
    EG_GET_UID, EG_GET_SOCIAL_NET, EG_GET_SOCIAL_ID, EG_GET_FIRST_NAME, EG_GET_LAST_NAME, 
    EG_GET_NICK_NAME, EG_GET_SEX, EG_GET_MUSIC, EG_GET_SOUND, EG_GET_ADMIN, EG_GET_LAST_JOIN_UTIME, 
    EG_GET_REGISTRATION_UTIME, EG_GET_LANGUAGE, EG_GET_INVITE_FRIENDS_COUNT, EG_GET_FRIENDS_DATA, 
    EG_GET_APP_FRIENDS_DATA, EG_GET_MONEY, EG_GET_GOLD, EG_GET_EXP, EG_GET_LVL, EG_MAX_ID
};
enum IG_Packets
{
    IG_MIN_ID = 10000, IG_JOIN = 10001, IG_GET_LOCATIONS_LIST = 10002, IG_START_LOCATION = 10003, IG_FINISH_LOCATION = 10004, IG_GET_BOSS_UPDATE = 10005,
    IG_KICK_BOSS = 10006, IG_EXCHANGE = 10007, IG_REQ_COLL = 10008, IG_MAX_ID
};
enum OG_Packets
{
    OG_MIN_ID = 20000, OG_USER_JSON = 20001, OG_SYNC = 20002, OG_ERROR = 20003, OG_MAX_ID
};
}
#endif